### PR TITLE
Fingerprint: Add permissions

### PR DESCRIPTION
**Pull request by xdevs23**

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Fingerprint won't work anyway :P

**Comment by xdevs23** [comment]
Already seen this?

```
D/fingerprintd: onAcquired(0)
D/FingerprintHAL: Authentication: got id 0x00000000 certainty 0
D/fingerprintd: onAuthenticated(fid=0, gid=1189641421)
D/QSEECOMAPI: : QSEECom_dealloc_memory 
D/QSEECOMAPI: : QSEECom_shutdown_app, app_id = 16
D/FingerprintHAL-QSEECom: QSEECom app fingerprints unloaded
```

I think the problem is

```
D/FingerprintHAL: Authentication: got id 0x00000000 certainty 0
```

**Comment by TheCrazyLex** [comment]
Indeed this is a good fix  and will be merged:) 

But will be difficult to make the FP work...

**Comment by xdevs23** [comment]
Thanks. Yeah I am often looking if there's any way to improve it.

**Comment by maniac103** [comment]
@xdevs23 The most promising approach to getting it work is installing a stock ROM, installing an instrumented kernel (with debug output in the qseecom driver dumping input and output buffers), looking at the communication done by the stock fingerprint code and trying to understand that. Just using the protocol used by some other random device won't work, as the log snippet above shows.

(it's way more promising than some random code formatting changes ;) )

**Comment by xdevs23** [comment]
That is definitively true. But as sorry as I am, I don't have much experience with that stuff. I had edited some boot/recovery images a while ago (init.rc / twrp themes) but I didn't get much of it.
I only saw in this rc file that the permissions for the (important?) fpc files were not set. So I just set them to rwxr-xr-x. If you think rw------- would be better, just do it.

**Comment by xdevs23** [comment]
Also did you see the file `/data/system/users/0/settings_fingerprint.xml`, the directory `/data/system/users/0/fpdata/` and the file `/data/misc/fp/metadata`, which could be interesting?

**Comment by maniac103** [comment]
- /data/system/users/0/fpdata/ is the directory Android wants the FP data to be stored in (needs to be supported by the TZ app)
- /data/misc/fp/metadata is written by the HAL itself
- /data/system/users/0/settings_fingerprint.xml includes a list of enrolled fingerprints, whose IDs were once returned by the HAL

Believe me, there's no way to make the FP sensor work (with a given vendor compiled TZ app) other than what I outlined above. There won't be a magical answer in any of the files in /data.

**Comment by xdevs23** [comment]
But the directory /data/system/users/0/fpdata/ is empty, even though I have saved a fingerprint.

**Comment by maniac103** [comment]
Yes, that's why I wrote 'needs to be supported by the TZ app'.

**Comment by xdevs23** [comment]
Aah right, now I understand, thx for clarifying.

**Pull request closed without merging**
